accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

dc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/detail', views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/<int:comment_id>/comment/delete/', views.comment_delete, name='comment_delete'),
    path('search/', views.search, name="search"),
    path('<int:id>/like/', views.like, name='like'),
    path('<int:id>/hate/', views.hate, name='hate'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateField(auto_now=True)
    edit_time = models.DateField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    hate_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="hate_posts")



class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ('title', 'content',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


def logout(reqeust):
    auth_logout(reqeust)
    return redirect('posts:index')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from django.db.models import Q

# Create your views here.


def index(request):
    posts = Post.objects.all().order_by('-id')
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/form.html', context)


def detail(request, id):
    post = get_object_or_404(Post, id=id)
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def update(request, id):
    post = get_object_or_404(Post, id=id)
    if post.user == request.user:
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
                return redirect('posts:detail', id)
        else:
            form = PostForm(instance=post)
        context = {
            'form': form,
        }
        return render(request, 'posts/form.html', context)
    else:
        return redirect('posts:detail', id)


@login_required
def delete(request, id):
    post = get_object_or_404(Post, id=id)
    if post.user == request.user:
        if request.method == 'POST':
            post.delete()
            return redirect('posts:index')
    else:
        return redirect('posts:detail', id)


@login_required
def comment_create(request, post_id):
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post_id = post_id
            comment.save()
            return redirect('posts:detail', post_id)


@login_required
def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.user == request.user:
        if request.method == 'POST':
            comment.delete()
    return redirect('posts:detail', post_id)
    

def search(request):
    target = request.GET.get('search')
    posts = Post.objects.all().filter(Q(title__contains=target) | Q(content__contains=target)).order_by('-id')
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)
    
def like(request, id):
    post = get_object_or_404(Post, id=id)
    user = request.user
    if post.like_users.filter(id=user.id):
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect('posts:detail', id)

def hate(request, id):
    post = get_object_or_404(Post, id=id)
    user = request.user
    if post.hate_users.filter(id=user.id):
        post.hate_users.remove(user)
    else:
        post.hate_users.add(user)
    return redirect('posts:detail', id)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <div class="border p-5" style="border-color: #4A56A8; position: relative; top: 150px;">
    <form action="" method='post'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
  </div>
{% endblock %}

dc/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SSAFY 갤러리</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/e87731a046.js" crossorigin="anonymous"></script>
  <style>
    .navbar-brand  {
      position: relative;
      left: -200px;
      top: 0;
    }
    body {
      font-family: '굴림';
    }
  </style>
  <link rel="shortcut icon" href="https://nstatic.dcinside.com/dc/w/images/logo_icon.ico">
</head>
<body>
  <div class="d-flex justify-content-center m-3">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><img src="https://nstatic.dcinside.com/dc/w/images/dcin_logo.png" alt="디시"></a>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4A56A8;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <form class="form-inline" action="{% url 'posts:search' %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='search'>
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
      </div>
    </nav>
  </div>
  <div class="py-3 px-5" style="background-color: #4A56A8; font-weight: bold;">
    {% if request.user.is_authenticated %}
    <a class="text-warning ml-5" href="{% url 'posts:create' %}">새 글 작성</a>
    <a class="text-light mx-1" href="{% url 'accounts:logout' %}">logout</a>
    {% else %}
    <a class="text-light ml-5" href="{% url 'accounts:signup' %}">signup</a>
    <a class="text-light mx-1" href="{% url 'accounts:login' %}">login</a>
    {% endif %}
  </div>
  <div class="m-2" style="width: 150px;">
    <a href="https://lineagem.plaync.com/">
      <img src="https://tpc.googlesyndication.com/simgad/7302563244461929925?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&rs=AOga4qmlm_AUpJYzszTfiGzIQ_cD0RFbLg" alt="" style="position: fixed; left: 150px;">
    </a>
  </div>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <a href="https://lineagem.plaync.com/">
    <img src="https://tpc.googlesyndication.com/simgad/12228884216589027432?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&rs=AOga4qlHknxcjsJnK-MXPUv0UGai92Z0KQ" alt="" style="position: absolute; right: 70px; top: 150px;">
  </a>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
</body>
</html>

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <h3 class="mt-4" style="color: #4A56A8; font-weight: bold;">SSAFY 갤러리</h3>

  <table class="table my-3">
    <thead>
      <tr>
        <th scope="col">{{post.title}}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{post.user}} | {{post.edit_time}}</td>
      </tr>
      <tr>
        <td>{{post.content}}</td>
      </tr>
    </tbody>
  </table>
  <div class="d-flex justify-content-center align-items-center">
    <p class="mx-1">{{ post.like_users.count }}</p>
    <a href="{% url 'posts:like' post.id %}" class="btn text-light mx-1 rounded-circle d-flex align-items-center" style="background-color: #4A56A8; width: 60px; height: 60px;" type="submit">개념</a>
    <a href="{% url 'posts:hate' post.id %}" class="btn text-light mx-1 rounded-circle d-flex align-items-center" style="background-color: gray; width: 60px; height: 60px;" type="submit">비추</a>
    <p class="mx-1">{{ post.hate_users.count }}</p>
  </div>
  <hr class="mb-3" style="border-color: #4A56A8; border-width: 2px;">

  {% for comment in post.comment_set.all %}
    <div class="d-inline-flex align-items-center my-1">
      <div style="width: 130px;">{{comment.user}}</div>
      <div class="d-flex justify-content-between align-items-center" style="width: 955px;">
        <div>{{comment.content}}</div>
        {% if comment.user == request.user %}
          <form action="{% url 'posts:comment_delete' post.id comment.id %}" method="POST">
            {% csrf_token %}
            <input class="btn text-light mx-1" style="background-color: #4A56A8;" type="submit" value="삭제">
          </form>
        {% endif %}
      </div>
    </div>
  {% endfor %}

  <hr class="mb-3" style="border-color: #4A56A8; border-width: 2px;">

  <form action="{% url 'posts:comment_create' post.id %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <div class="d-flex flex-row-reverse">
    <input class="btn text-light mx-1" style="background-color: #4A56A8;" type="submit" value="등록">
    </div>
  </form>

  <hr class="mb-3" style="border-color: #4A56A8; border-width: 2px;">

  <div class="d-flex flex-row-reverse">
    <a href="{% url 'posts:create' %}" class="btn text-light mx-1" style="background-color: #4A56A8;">글쓰기</a>
    {% if post.user == request.user %}
      <a class="btn text-light mx-1" style="background-color: #4A56A8;" href="{% url 'posts:update' post.id %}">수정</a>
      <form action="{% url 'posts:delete' post.id %}" method='post'>
        {% csrf_token %}
        <input class="btn text-light mx-1" style="background-color: #4A56A8;" type="submit" value="삭제">
      </form>
    {% endif %}
  </div>

  <table class="table mt-5 table-sm">
    <thead>
      <tr>
        <th scope="col">번호</th>
        <th scope="col">제목</th>
        <th scope="col">글쓴이</th>
        <th scope="col">작성일</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <th scope="row">{{post.id}}</th>
        <td><a class="text-dark" href="{% url 'posts:detail' post.id %}">{{post.title}}</a></td>
        <td>{{post.user}}</td>
        <td>{{post.date}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
  <div class="d-flex flex-row-reverse mb-3">
    <a href="{% url 'posts:create' %}" class="btn text-light" style="background-color: #4A56A8;">글쓰기</a>
  </div>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <div class="jumbotron my-3">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-flex flex-row-reverse">
      <input class="btn text-light mx-1" style="background-color: #4A56A8;" type="submit" value="등록">
      </div>
    </form>
  </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
  <h3 class="mt-4" style="color: #4A56A8; font-weight: bold;">SSAFY 갤러리</h3>
  <a href="https://gall.dcinside.com/board/lists/?id=tree">
    <img src="{% static 'deco.jpg' %}" alt="">
  </a>
  <table class="table mt-5">
    <thead>
      <tr>
        <th scope="col">번호</th>
        <th scope="col">제목</th>
        <th scope="col">글쓴이</th>
        <th scope="col">작성일</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <th scope="row">{{post.id}}</th>
        <td><a class="text-dark" href="{% url 'posts:detail' post.id %}">{{post.title}} [{{post.comment_set.count}}]</a></td>
        <td>{{post.user}}</td>
        <td>{{post.date|date:'Y.m.d'}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="d-flex flex-row-reverse mb-3">
    <a href="{% url 'posts:create' %}" class="btn text-light" style="background-color: #4A56A8;">글쓰기</a>
  </div>
{% endblock %}